### PR TITLE
win,tty: Add set cursor style to CSI sequences

### PR DESCRIPTION
**Pull request by erw7**

### CODE REVIEW

**Comment by blueyed** [comment]
@erw7 
What about this and other patches?
Have they been sent upstream?

Current diff (from update for v1.30.0): https://github.com/libuv/libuv/compare/v1.x...blueyed:update?expand=1

**Comment by justinmk** [comment]
@blueyed https://github.com/libuv/libuv/pulls/erw7 

It has been difficult getting upstream to focus on those PRs :(

**Comment by blueyed** [comment]
I see.
Should we use our fork then also for non-Windows?  (I found it confusing to use it only for Windows, and this would it more consistent and also tested on Travis then)

**Comment by justinmk** [comment]
> Should we use our fork then also for non-Windows? (I found it confusing to use it only for Windows, and this would it more consistent and also tested on Travis then)

No. That would be far more confusing, because distros aren't going to package our fork. (Nor would I want them to, it makes no sense).

What's confusing about it, anyway? We have to make exceptions for Windows. Bringing all of those exceptions onto every other platform doesn't help anything.

Our fork is:

-  alternative to maintaining a bunch of cmake `PATCH_COMMAND` steps, which is much more brittle.
- **temporary**. We want the fork to go away, we are waiting for upstream libuv.

**Pull request merged**
